### ISSUE TITLE
UI Login doesn't work

### ISSUE THREAD

**Issue by Hyruma** [aws/aws-mwaa-local-runner#10] opened 2021-05-26 10:32 UTC
Hello, 

I followed all the steps in the readme and when I access the login page using the credentials 'admin' 'test' nothing happens. I try to get to the homepage but I continue to have the login fields

```
local-runner_1  | 172.18.0.1 - - [26/May/2021:10:35:50 +0000] "POST /login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome HTTP/1.1" 302 209 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
local-runner_1  | 172.18.0.1 - - [26/May/2021:10:35:50 +0000] "GET / HTTP/1.1" 302 217 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
local-runner_1  | 172.18.0.1 - - [26/May/2021:10:35:50 +0000] "GET /home HTTP/1.1" 302 305 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
local-runner_1  | 172.18.0.1 - - [26/May/2021:10:35:51 +0000] "GET /login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome HTTP/1.1" 200 17126 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

```

![image](https://user-images.githubusercontent.com/12028752/119644935-c5652000-be1d-11eb-9300-13174341ee42.png)

**Comment by zdjohn** [comment] 2021-06-02 06:50
same problem here, seems the page keeps redirecting

**Comment by marcoracer** [comment] 2021-06-02 20:10
same problem... tested with chrome, firefox and Safari

**Comment by lizdeika** [comment] 2021-06-07 12:02
I have the same issue, no way to login :(

**Comment by bdebenon** [comment] 2021-06-08 06:59
Same Issue:
![image](https://user-images.githubusercontent.com/25289031/121138323-2f59ce00-c7fd-11eb-9c43-f40912a27d8e.png)

**Comment by sashaegorov** [comment] 2021-06-10 13:24
Hey, the same thing for me.

**Comment by cjames23** [comment] 2021-06-11 19:07
Can you provide which version of the local runner you are using?

**Comment by zdjohn** [comment] 2021-06-11 23:11
@cjames23  `image: amazon/mwaa-local:2.0` this is my version for local runner. if that's your question
OS: ubuntu 20.04

**Comment by cjames23** [comment] 2021-06-12 00:06
@zdjohn thank you, this will help with trying to reproduce the error to figure out what the root cause is.

**Comment by mtkociuba** [comment] 2021-06-12 23:47
Can confirm, login doesnt work

**Comment by knowsuchagency** [comment] 2021-06-15 04:34
Same. Configuring airflow to provide more log output doesn't help either

```docker-compose
local-runner:
        image: amazon/mwaa-local:2.0
        restart: always
        depends_on:
            - postgres
        environment:
            ...
            - AIRFLOW_LOGGING_LOG_LEVEL=DEBUG
            - AIRFLOW_LOGGING_FAB_LOGGING_LEVEL=DEBUG
```

**Comment by knowsuchagency** [comment] 2021-06-17 00:54
To clarify, this is on MacOS for me

**Comment by knowsuchagency** [comment] 2021-06-17 04:42
We were able to resolve this by adding `AUTH_ROLE_PUBLIC = "Admin"` to `docker/config/webserver_config.py`

and commenting out `airflow users create -r Admin -u admin -e admin@example.com -f admin -l user -p test` in `docker/script/entrypoint.sh`

**Comment by cjames23** [comment] 2021-06-17 04:52
Interesting, I am running it on macOS without any problems. I plan to have some time this weekend finally to take a look at it.

**Comment by bdebenon** [comment] 2021-06-17 16:08
@cjames23 It appears to be an intermittent issue. Not quite sure what specifically triggers it though. Also, if you reboot your computer it tends to resolve itself (I am also using macOS).

**Comment by subashcanapathy** [comment] 2021-06-17 21:39
there are 2 theories we have so far, one of it confirmed 
1. Browser's privacy settings preventing post auth redirect. (need more analysis on why some ppl observe this esp more prevalent on firefox than chrome)
2. (Confirmed) users who used this setup on a remote/cloud host and tried to access using hostname:port will have this problem as the configuration on the package was hard coded to localhost:8080 and without setting port forwarding or proxy on the ec2 instance, the URL wont work

**Comment by subashcanapathy** [comment] 2021-06-17 21:39
there are 2 theories we have so far, one of it confirmed 
1. Browser's privacy settings preventing post auth redirect. (need more analysis on why some ppl observe this esp more prevalent on firefox than chrome)
2. (Confirmed) users who used this setup on a remote/cloud host and tried to access using hostname:port will have this problem as the configuration on the package was hard coded to localhost:8080 and without setting port forwarding or proxy on the ec2 instance, the URL wont work

**Comment by aws-sagar** [comment] 2021-06-17 21:47
Adding to @subashcanapathy 's point. The below steps worked for me on an ec2 instance.

Via local port forwarding (you don't need the proxy):

> Setup tunnel + local port forwarding
> `ssh -i "/path/to/pem" user@ec2-dns -L 8157:ec2-dns:8080`
> 
> Once the image is built with `./mwaa-local-env build-image`, run below
>  `./mwaa-local-env start`
>
> Access the UI http://localhost:8157/

**Comment by manypozo** [comment] 2021-07-13 08:01
I have also noticed this.
Accessing to `http://0.0.0.0:8080`  and performing logging operations leaded into an endless forwarding into the logging page.

The stdout logger shows both the successfull logging and the redirection.
``` 
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-07-12 08:04:51,397] {{dagbag.py:451}} INFO - Filling up the DagBag from /dev/null
[2021-07-12 08:04:53 +0000] [225] [INFO] Starting gunicorn 19.10.0
[2021-07-12 08:04:53 +0000] [225] [INFO] Listening at: http://0.0.0.0:8080 (225)
[2021-07-12 08:04:53 +0000] [225] [INFO] Using worker: sync
[2021-07-12 08:04:53 +0000] [228] [INFO] Booting worker with pid: 228
[2021-07-12 08:04:53 +0000] [229] [INFO] Booting worker with pid: 229
[2021-07-12 08:04:53 +0000] [230] [INFO] Booting worker with pid: 230
[2021-07-12 08:04:53 +0000] [231] [INFO] Booting worker with pid: 231
172.28.0.1 - - [12/Jul/2021:08:05:09 +0000] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:09 +0000] "GET /home HTTP/1.1" 302 301 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:10 +0000] "GET /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 200 16873 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:14 +0000] "POST /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 302 209 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:14 +0000] "GET / HTTP/1.1" 302 217 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:14 +0000] "GET /home HTTP/1.1" 302 301 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:14 +0000] "GET /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 200 16873 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
[2021-07-12 08:05:24 +0000] [225] [INFO] Handling signal: ttin
[2021-07-12 08:05:24 +0000] [277] [INFO] Booting worker with pid: 277
172.28.0.1 - - [12/Jul/2021:08:05:25 +0000] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:25 +0000] "GET /home HTTP/1.1" 302 301 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:25 +0000] "GET /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 200 16873 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
[2021-07-12 08:05:29 +0000] [225] [INFO] Handling signal: ttou
[2021-07-12 08:05:29 +0000] [228] [INFO] Worker exiting (pid: 228)
172.28.0.1 - - [12/Jul/2021:08:05:32 +0000] "POST /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 302 209 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:32 +0000] "GET / HTTP/1.1" 302 217 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:32 +0000] "GET /home HTTP/1.1" 302 301 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:32 +0000] "GET /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 200 16873 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:37 +0000] "GET / HTTP/1.1" 302 217 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:37 +0000] "GET /home HTTP/1.1" 302 301 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.28.0.1 - - [12/Jul/2021:08:05:37 +0000] "GET /login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome HTTP/1.1" 200 16873 "http://0.0.0.0:8080/login/?next=http%3A%2F%2F0.0.0.0%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
```

I also noticed this happenened when I had other aws-mwaa-local-runner-webui tab openened in the browser.

Instead of copy pasting the UR `http://0.0.0.0:8080` or clicling on the link from stdout, I just wentto my bwoser and type `http://localhost:8080`. I have neved had the issue again so far. 

This is not much, but hope it helps

**Comment by vicmerlis** [comment] 2021-08-05 13:31
> We were able to resolve this by adding `AUTH_ROLE_PUBLIC = "Admin"` to `docker/config/webserver_config.py`
> 
> and commenting out `airflow users create -r Admin -u admin -e admin@example.com -f admin -l user -p test` in `docker/script/entrypoint.sh`

Working! Thanks!
Maybe worth to mention that you need to run `./mwaa-local-env build-image` after these changes.

**Comment by zdjohn** [comment] 2021-08-12 00:55
shall we put up a PR for this fix? happy to do that

**Comment by fredb-gc** [comment] 2022-02-14 10:30
Also getting this issue on MacOS, but the above suggestion works for me:

> We were able to resolve this by adding `AUTH_ROLE_PUBLIC = "Admin"` to `docker/config/webserver_config.py`
> 
> and commenting out `airflow users create -r Admin -u admin -e admin@example.com -f admin -l user -p test` in `docker/script/entrypoint.sh`

**Comment by john-jac** [comment] 2022-09-27 20:06
Fixed in https://github.com/aws/aws-mwaa-local-runner/pull/147

**Closed by john-jac** 2022-09-27 20:06 UTC
